### ISSUE TITLE
READMEを書く

### ISSUE THREAD

**Issue by book000** [book000/twitter-rss#1047]

**Comment by ozbillwang** [comment]
yes, README please.

There is no TWITTER_USERNAME and TWITTER_PASSWORD I can provide, I login via gmail SSO
```
 yarn run dev
yarn run v1.22.19
$ ts-node-dev -r tsconfig-paths/register ./src/main.ts
[INFO] 20:05:44 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.2, typescript ver. 5.6.3)
[2024-11-18 18:05:47.711] [generateRSS/INFO]: 🚀 Generating RSS...
[2024-11-18 18:05:47.731] [main/ERROR]: unhandledRejection TWITTER_USERNAME, TWITTER_PASSWORD is not set
    at generateRSS (/Users/bill/study/github/book000/twitter-rss/src/main.ts:44:11)
    at main (/Users/bill/study/github/book000/twitter-rss/src/main.ts:215:9)
```

**Comment by ozbillwang** [comment]
I have applied an account with username and password. 

Now it goes further. 

<img width="1327" alt="image" src="https://github.com/user-attachments/assets/37c38cc0-fd2f-45f9-9009-167c61459089">

In the backend, seems the tool will automatically login twitter and collect the posts. 

what's the next step? I don't see any webpage pop up?

Second, if I need get other posts, for example, Elon Musk, what configuration file I should update?

**Comment by ozbillwang** [comment]
let me write the README for you.

**Comment by book000** [comment]
Glad it worked well!
