### ISSUE TITLE
several questions after I successfully run this project

### ISSUE THREAD

**Issue by ozbillwang** [book000/twitter-rss#1884]
1. How can I keep getting updates from target accounts? for example, I set the target account to `Elon Musk`

```
{
  "Elon Musk": "from:elonmusk"
}
```

How to refresh the contents reguarly?

2. support **quiet mode**?

When run this tool, it pops with default browser, then auto-login, collect posts. 

could we set a quiet mode, without any pop websites, and get the posts and save to `output` directly?

**Comment by book000** [comment]
@ozbillwang This project & application is currently in the generate of RSS feeds of Twitter search results that I would like to collect.
The operation is then collected and updated by GitHub Actions.

A definition of this behavior can be found: https://github.com/book000/twitter-rss/blob/master/.github/workflows/update-rss.yml
And this is delivered: https://book000.github.io/twitter-rss/

If you want to implement something similar, you will need to fork this project, activate GitHub Actions, and then update your environment variables and configuration files appropriately.

---

Then I will answer your questions.

> 1. How can I keep getting updates from target accounts? for example, I set the target account to Elon Musk

The only way to do this is to run the program regularly by some means. There are several ways to do this, in my case I employed GitHub Actions.
The advantage is that there is no limit to the cumulative execution time if it is a public repository.
I think another option would be to purchase or rent a server, to run the program.

> 2. support quiet mode?

I use a library called [puppeteer](https://pptr.dev/) to make the browser run automatically. It has a mode called [“headless mode”](https://pptr.dev/guides/headless-modes) that allows it to run without displaying a screen.
However, Twitter detects this, so this method cannot be used.

A workaround is to use a virtual display server. In my case, I use [Xvfb](https://en.wikipedia.org/wiki/Xvfb).

**Comment by ozbillwang** [comment]
thanks, for item 1, I am fine to set the scheduler. 

For item 2, quiet mode. Seems you can run your tool in docker, that means quiet mode already, right? Because you can't start X display in docker container. 

Let me take a try.

**Comment by book000** [comment]
Hi @ozbillwang, It has been two weeks since our last conversation on this issue.
I believe I have answered your all questions, what about you?
If you have no problem, I would like to close this issue.
